// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: core.proto

package qubicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *EntityInfo_Entity     `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	ValidForTick  uint32                 `protobuf:"varint,2,opt,name=valid_for_tick,json=validForTick,proto3" json:"valid_for_tick,omitempty"`
	SpectrumIndex int32                  `protobuf:"varint,3,opt,name=spectrum_index,json=spectrumIndex,proto3" json:"spectrum_index,omitempty"`
	SiblingIds    []string               `protobuf:"bytes,4,rep,name=sibling_ids,json=siblingIds,proto3" json:"sibling_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *EntityInfo) GetEntity() *EntityInfo_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityInfo) GetValidForTick() uint32 {
	if x != nil {
		return x.ValidForTick
	}
	return 0
}

func (x *EntityInfo) GetSpectrumIndex() int32 {
	if x != nil {
		return x.SpectrumIndex
	}
	return 0
}

func (x *EntityInfo) GetSiblingIds() []string {
	if x != nil {
		return x.SiblingIds
	}
	return nil
}

type Computors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Computors) Reset() {
	*x = Computors{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Computors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Computors) ProtoMessage() {}

func (x *Computors) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Computors.ProtoReflect.Descriptor instead.
func (*Computors) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *Computors) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Computors) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *Computors) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Computors) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type QuorumVote struct {
	state                       protoimpl.MessageState            `protogen:"open.v1"`
	SharedVotes                 []*QuorumVote_GroupedSharedVotes  `protobuf:"bytes,1,rep,name=shared_votes,json=sharedVotes,proto3" json:"shared_votes,omitempty"`
	SaltedVotesPerComputorIndex map[uint32]*QuorumVote_SaltedVote `protobuf:"bytes,2,rep,name=salted_votes_per_computor_index,json=saltedVotesPerComputorIndex,proto3" json:"salted_votes_per_computor_index,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *QuorumVote) Reset() {
	*x = QuorumVote{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumVote) ProtoMessage() {}

func (x *QuorumVote) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumVote.ProtoReflect.Descriptor instead.
func (*QuorumVote) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *QuorumVote) GetSharedVotes() []*QuorumVote_GroupedSharedVotes {
	if x != nil {
		return x.SharedVotes
	}
	return nil
}

func (x *QuorumVote) GetSaltedVotesPerComputorIndex() map[uint32]*QuorumVote_SaltedVote {
	if x != nil {
		return x.SaltedVotesPerComputorIndex
	}
	return nil
}

type TickData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComputorIndex  uint32                 `protobuf:"varint,1,opt,name=computor_index,json=computorIndex,proto3" json:"computor_index,omitempty"`
	Epoch          uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Tick           uint32                 `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	VarStruct      string                 `protobuf:"bytes,5,opt,name=var_struct,json=varStruct,proto3" json:"var_struct,omitempty"`
	TimeLock       string                 `protobuf:"bytes,6,opt,name=time_lock,json=timeLock,proto3" json:"time_lock,omitempty"`
	TransactionIds []string               `protobuf:"bytes,7,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	ContractFees   []int64                `protobuf:"varint,8,rep,packed,name=contract_fees,json=contractFees,proto3" json:"contract_fees,omitempty"`
	Signature      string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TickData) Reset() {
	*x = TickData{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickData) ProtoMessage() {}

func (x *TickData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickData.ProtoReflect.Descriptor instead.
func (*TickData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *TickData) GetComputorIndex() uint32 {
	if x != nil {
		return x.ComputorIndex
	}
	return 0
}

func (x *TickData) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TickData) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TickData) GetVarStruct() string {
	if x != nil {
		return x.VarStruct
	}
	return ""
}

func (x *TickData) GetTimeLock() string {
	if x != nil {
		return x.TimeLock
	}
	return ""
}

func (x *TickData) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

func (x *TickData) GetContractFees() []int64 {
	if x != nil {
		return x.ContractFees
	}
	return nil
}

func (x *TickData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type TickInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Tick                    uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	DurationInSeconds       uint32                 `protobuf:"varint,2,opt,name=duration_in_seconds,json=durationInSeconds,proto3" json:"duration_in_seconds,omitempty"`
	Epoch                   uint32                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NumberOfAlignedVotes    uint32                 `protobuf:"varint,4,opt,name=number_of_aligned_votes,json=numberOfAlignedVotes,proto3" json:"number_of_aligned_votes,omitempty"`
	NumberOfMisalignedVotes uint32                 `protobuf:"varint,5,opt,name=number_of_misaligned_votes,json=numberOfMisalignedVotes,proto3" json:"number_of_misaligned_votes,omitempty"`
	InitialTickOfEpoch      uint32                 `protobuf:"varint,6,opt,name=initial_tick_of_epoch,json=initialTickOfEpoch,proto3" json:"initial_tick_of_epoch,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TickInfo) Reset() {
	*x = TickInfo{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickInfo) ProtoMessage() {}

func (x *TickInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickInfo.ProtoReflect.Descriptor instead.
func (*TickInfo) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *TickInfo) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickInfo) GetDurationInSeconds() uint32 {
	if x != nil {
		return x.DurationInSeconds
	}
	return 0
}

func (x *TickInfo) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TickInfo) GetNumberOfAlignedVotes() uint32 {
	if x != nil {
		return x.NumberOfAlignedVotes
	}
	return 0
}

func (x *TickInfo) GetNumberOfMisalignedVotes() uint32 {
	if x != nil {
		return x.NumberOfMisalignedVotes
	}
	return 0
}

func (x *TickInfo) GetInitialTickOfEpoch() uint32 {
	if x != nil {
		return x.InitialTickOfEpoch
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId        string                 `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Tick          uint32                 `protobuf:"varint,4,opt,name=tick,proto3" json:"tick,omitempty"`
	InputType     uint32                 `protobuf:"varint,5,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputSize     uint32                 `protobuf:"varint,6,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	Input         string                 `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Signature     string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	TxId          string                 `protobuf:"bytes,9,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Digest        string                 `protobuf:"bytes,10,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *Transaction) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Transaction) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Transaction) GetInputType() uint32 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *Transaction) GetInputSize() uint32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *Transaction) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Transaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Transaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Transaction) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type TickTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickTransactions) Reset() {
	*x = TickTransactions{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickTransactions) ProtoMessage() {}

func (x *TickTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickTransactions.ProtoReflect.Descriptor instead.
func (*TickTransactions) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *TickTransactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TickTransactionsStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tick              uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	CurrentTickOfNode uint32                 `protobuf:"varint,2,opt,name=current_tick_of_node,json=currentTickOfNode,proto3" json:"current_tick_of_node,omitempty"`
	TxCount           uint32                 `protobuf:"varint,3,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	StatusPerTx       map[string]bool        `protobuf:"bytes,4,rep,name=status_per_tx,json=statusPerTx,proto3" json:"status_per_tx,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TickTransactionsStatus) Reset() {
	*x = TickTransactionsStatus{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickTransactionsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickTransactionsStatus) ProtoMessage() {}

func (x *TickTransactionsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickTransactionsStatus.ProtoReflect.Descriptor instead.
func (*TickTransactionsStatus) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *TickTransactionsStatus) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickTransactionsStatus) GetCurrentTickOfNode() uint32 {
	if x != nil {
		return x.CurrentTickOfNode
	}
	return 0
}

func (x *TickTransactionsStatus) GetTxCount() uint32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *TickTransactionsStatus) GetStatusPerTx() map[string]bool {
	if x != nil {
		return x.StatusPerTx
	}
	return nil
}

type EntityInfo_Entity struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncomingAmount             int64                  `protobuf:"varint,2,opt,name=incoming_amount,json=incomingAmount,proto3" json:"incoming_amount,omitempty"`
	OutgoingAmount             int64                  `protobuf:"varint,3,opt,name=outgoing_amount,json=outgoingAmount,proto3" json:"outgoing_amount,omitempty"`
	NumberOfIncomingTransfers  uint32                 `protobuf:"varint,4,opt,name=number_of_incoming_transfers,json=numberOfIncomingTransfers,proto3" json:"number_of_incoming_transfers,omitempty"`
	NumberOfOutgoingTransfers  uint32                 `protobuf:"varint,5,opt,name=number_of_outgoing_transfers,json=numberOfOutgoingTransfers,proto3" json:"number_of_outgoing_transfers,omitempty"`
	LatestIncomingTransferTick uint32                 `protobuf:"varint,6,opt,name=latest_incoming_transfer_tick,json=latestIncomingTransferTick,proto3" json:"latest_incoming_transfer_tick,omitempty"`
	LatestOutgoingTransferTick uint32                 `protobuf:"varint,7,opt,name=latest_outgoing_transfer_tick,json=latestOutgoingTransferTick,proto3" json:"latest_outgoing_transfer_tick,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *EntityInfo_Entity) Reset() {
	*x = EntityInfo_Entity{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo_Entity) ProtoMessage() {}

func (x *EntityInfo_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo_Entity.ProtoReflect.Descriptor instead.
func (*EntityInfo_Entity) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EntityInfo_Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityInfo_Entity) GetIncomingAmount() int64 {
	if x != nil {
		return x.IncomingAmount
	}
	return 0
}

func (x *EntityInfo_Entity) GetOutgoingAmount() int64 {
	if x != nil {
		return x.OutgoingAmount
	}
	return 0
}

func (x *EntityInfo_Entity) GetNumberOfIncomingTransfers() uint32 {
	if x != nil {
		return x.NumberOfIncomingTransfers
	}
	return 0
}

func (x *EntityInfo_Entity) GetNumberOfOutgoingTransfers() uint32 {
	if x != nil {
		return x.NumberOfOutgoingTransfers
	}
	return 0
}

func (x *EntityInfo_Entity) GetLatestIncomingTransferTick() uint32 {
	if x != nil {
		return x.LatestIncomingTransferTick
	}
	return 0
}

func (x *EntityInfo_Entity) GetLatestOutgoingTransferTick() uint32 {
	if x != nil {
		return x.LatestOutgoingTransferTick
	}
	return 0
}

type QuorumVote_SharedVote struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Epoch                     uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Tick                      uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Timestamp                 *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevResourceTestingDigest string                 `protobuf:"bytes,5,opt,name=prev_resource_testing_digest,json=prevResourceTestingDigest,proto3" json:"prev_resource_testing_digest,omitempty"`
	PrevSpectrumDigest        string                 `protobuf:"bytes,6,opt,name=prev_spectrum_digest,json=prevSpectrumDigest,proto3" json:"prev_spectrum_digest,omitempty"`
	PrevUniverseDigest        string                 `protobuf:"bytes,7,opt,name=prev_universe_digest,json=prevUniverseDigest,proto3" json:"prev_universe_digest,omitempty"`
	PrevComputerDigest        string                 `protobuf:"bytes,8,opt,name=prev_computer_digest,json=prevComputerDigest,proto3" json:"prev_computer_digest,omitempty"`
	TxDigest                  string                 `protobuf:"bytes,9,opt,name=tx_digest,json=txDigest,proto3" json:"tx_digest,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *QuorumVote_SharedVote) Reset() {
	*x = QuorumVote_SharedVote{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumVote_SharedVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumVote_SharedVote) ProtoMessage() {}

func (x *QuorumVote_SharedVote) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumVote_SharedVote.ProtoReflect.Descriptor instead.
func (*QuorumVote_SharedVote) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2, 0}
}

func (x *QuorumVote_SharedVote) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *QuorumVote_SharedVote) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *QuorumVote_SharedVote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *QuorumVote_SharedVote) GetPrevResourceTestingDigest() string {
	if x != nil {
		return x.PrevResourceTestingDigest
	}
	return ""
}

func (x *QuorumVote_SharedVote) GetPrevSpectrumDigest() string {
	if x != nil {
		return x.PrevSpectrumDigest
	}
	return ""
}

func (x *QuorumVote_SharedVote) GetPrevUniverseDigest() string {
	if x != nil {
		return x.PrevUniverseDigest
	}
	return ""
}

func (x *QuorumVote_SharedVote) GetPrevComputerDigest() string {
	if x != nil {
		return x.PrevComputerDigest
	}
	return ""
}

func (x *QuorumVote_SharedVote) GetTxDigest() string {
	if x != nil {
		return x.TxDigest
	}
	return ""
}

type QuorumVote_GroupedSharedVotes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          *QuorumVote_SharedVote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	NumberOfVotes int32                  `protobuf:"varint,2,opt,name=number_of_votes,json=numberOfVotes,proto3" json:"number_of_votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumVote_GroupedSharedVotes) Reset() {
	*x = QuorumVote_GroupedSharedVotes{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumVote_GroupedSharedVotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumVote_GroupedSharedVotes) ProtoMessage() {}

func (x *QuorumVote_GroupedSharedVotes) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumVote_GroupedSharedVotes.ProtoReflect.Descriptor instead.
func (*QuorumVote_GroupedSharedVotes) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2, 1}
}

func (x *QuorumVote_GroupedSharedVotes) GetVote() *QuorumVote_SharedVote {
	if x != nil {
		return x.Vote
	}
	return nil
}

func (x *QuorumVote_GroupedSharedVotes) GetNumberOfVotes() int32 {
	if x != nil {
		return x.NumberOfVotes
	}
	return 0
}

type QuorumVote_SaltedVote struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ResourceTestingDigest    string                 `protobuf:"bytes,1,opt,name=resource_testing_digest,json=resourceTestingDigest,proto3" json:"resource_testing_digest,omitempty"`
	SpectrumDigest           string                 `protobuf:"bytes,2,opt,name=spectrum_digest,json=spectrumDigest,proto3" json:"spectrum_digest,omitempty"`
	UniverseDigest           string                 `protobuf:"bytes,3,opt,name=universe_digest,json=universeDigest,proto3" json:"universe_digest,omitempty"`
	ComputerDigest           string                 `protobuf:"bytes,4,opt,name=computer_digest,json=computerDigest,proto3" json:"computer_digest,omitempty"`
	ExpectedNextTickTxDigest string                 `protobuf:"bytes,5,opt,name=expected_next_tick_tx_digest,json=expectedNextTickTxDigest,proto3" json:"expected_next_tick_tx_digest,omitempty"`
	Signature                string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QuorumVote_SaltedVote) Reset() {
	*x = QuorumVote_SaltedVote{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumVote_SaltedVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumVote_SaltedVote) ProtoMessage() {}

func (x *QuorumVote_SaltedVote) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumVote_SaltedVote.ProtoReflect.Descriptor instead.
func (*QuorumVote_SaltedVote) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2, 2}
}

func (x *QuorumVote_SaltedVote) GetResourceTestingDigest() string {
	if x != nil {
		return x.ResourceTestingDigest
	}
	return ""
}

func (x *QuorumVote_SaltedVote) GetSpectrumDigest() string {
	if x != nil {
		return x.SpectrumDigest
	}
	return ""
}

func (x *QuorumVote_SaltedVote) GetUniverseDigest() string {
	if x != nil {
		return x.UniverseDigest
	}
	return ""
}

func (x *QuorumVote_SaltedVote) GetComputerDigest() string {
	if x != nil {
		return x.ComputerDigest
	}
	return ""
}

func (x *QuorumVote_SaltedVote) GetExpectedNextTickTxDigest() string {
	if x != nil {
		return x.ExpectedNextTickTxDigest
	}
	return ""
}

func (x *QuorumVote_SaltedVote) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\bqubic.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x04\n" +
	"\n" +
	"EntityInfo\x123\n" +
	"\x06entity\x18\x01 \x01(\v2\x1b.qubic.v1.EntityInfo.EntityR\x06entity\x12$\n" +
	"\x0evalid_for_tick\x18\x02 \x01(\rR\fvalidForTick\x12%\n" +
	"\x0espectrum_index\x18\x03 \x01(\x05R\rspectrumIndex\x12\x1f\n" +
	"\vsibling_ids\x18\x04 \x03(\tR\n" +
	"siblingIds\x1a\xf2\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fincoming_amount\x18\x02 \x01(\x03R\x0eincomingAmount\x12'\n" +
	"\x0foutgoing_amount\x18\x03 \x01(\x03R\x0eoutgoingAmount\x12?\n" +
	"\x1cnumber_of_incoming_transfers\x18\x04 \x01(\rR\x19numberOfIncomingTransfers\x12?\n" +
	"\x1cnumber_of_outgoing_transfers\x18\x05 \x01(\rR\x19numberOfOutgoingTransfers\x12A\n" +
	"\x1dlatest_incoming_transfer_tick\x18\x06 \x01(\rR\x1alatestIncomingTransferTick\x12A\n" +
	"\x1dlatest_outgoing_transfer_tick\x18\a \x01(\rR\x1alatestOutgoingTransferTick\"w\n" +
	"\tComputors\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\xc0\b\n" +
	"\n" +
	"QuorumVote\x12J\n" +
	"\fshared_votes\x18\x01 \x03(\v2'.qubic.v1.QuorumVote.GroupedSharedVotesR\vsharedVotes\x12{\n" +
	"\x1fsalted_votes_per_computor_index\x18\x02 \x03(\v25.qubic.v1.QuorumVote.SaltedVotesPerComputorIndexEntryR\x1bsaltedVotesPerComputorIndex\x1a\xe4\x02\n" +
	"\n" +
	"SharedVote\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\x1cprev_resource_testing_digest\x18\x05 \x01(\tR\x19prevResourceTestingDigest\x120\n" +
	"\x14prev_spectrum_digest\x18\x06 \x01(\tR\x12prevSpectrumDigest\x120\n" +
	"\x14prev_universe_digest\x18\a \x01(\tR\x12prevUniverseDigest\x120\n" +
	"\x14prev_computer_digest\x18\b \x01(\tR\x12prevComputerDigest\x12\x1b\n" +
	"\ttx_digest\x18\t \x01(\tR\btxDigest\x1aq\n" +
	"\x12GroupedSharedVotes\x123\n" +
	"\x04vote\x18\x01 \x01(\v2\x1f.qubic.v1.QuorumVote.SharedVoteR\x04vote\x12&\n" +
	"\x0fnumber_of_votes\x18\x02 \x01(\x05R\rnumberOfVotes\x1a\x9d\x02\n" +
	"\n" +
	"SaltedVote\x126\n" +
	"\x17resource_testing_digest\x18\x01 \x01(\tR\x15resourceTestingDigest\x12'\n" +
	"\x0fspectrum_digest\x18\x02 \x01(\tR\x0espectrumDigest\x12'\n" +
	"\x0funiverse_digest\x18\x03 \x01(\tR\x0euniverseDigest\x12'\n" +
	"\x0fcomputer_digest\x18\x04 \x01(\tR\x0ecomputerDigest\x12>\n" +
	"\x1cexpected_next_tick_tx_digest\x18\x05 \x01(\tR\x18expectedNextTickTxDigest\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x1ao\n" +
	" SaltedVotesPerComputorIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.qubic.v1.QuorumVote.SaltedVoteR\x05value:\x028\x01\"\xbd\x02\n" +
	"\bTickData\x12%\n" +
	"\x0ecomputor_index\x18\x01 \x01(\rR\rcomputorIndex\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12\x12\n" +
	"\x04tick\x18\x03 \x01(\rR\x04tick\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"var_struct\x18\x05 \x01(\tR\tvarStruct\x12\x1b\n" +
	"\ttime_lock\x18\x06 \x01(\tR\btimeLock\x12'\n" +
	"\x0ftransaction_ids\x18\a \x03(\tR\x0etransactionIds\x12#\n" +
	"\rcontract_fees\x18\b \x03(\x03R\fcontractFees\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\"\x8b\x02\n" +
	"\bTickInfo\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12.\n" +
	"\x13duration_in_seconds\x18\x02 \x01(\rR\x11durationInSeconds\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x125\n" +
	"\x17number_of_aligned_votes\x18\x04 \x01(\rR\x14numberOfAlignedVotes\x12;\n" +
	"\x1anumber_of_misaligned_votes\x18\x05 \x01(\rR\x17numberOfMisalignedVotes\x121\n" +
	"\x15initial_tick_of_epoch\x18\x06 \x01(\rR\x12initialTickOfEpoch\"\x8e\x02\n" +
	"\vTransaction\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x17\n" +
	"\adest_id\x18\x02 \x01(\tR\x06destId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04tick\x18\x04 \x01(\rR\x04tick\x12\x1d\n" +
	"\n" +
	"input_type\x18\x05 \x01(\rR\tinputType\x12\x1d\n" +
	"\n" +
	"input_size\x18\x06 \x01(\rR\tinputSize\x12\x14\n" +
	"\x05input\x18\a \x01(\tR\x05input\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x13\n" +
	"\x05tx_id\x18\t \x01(\tR\x04txId\x12\x16\n" +
	"\x06digest\x18\n" +
	" \x01(\tR\x06digest\"M\n" +
	"\x10TickTransactions\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.qubic.v1.TransactionR\ftransactions\"\x8f\x02\n" +
	"\x16TickTransactionsStatus\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12/\n" +
	"\x14current_tick_of_node\x18\x02 \x01(\rR\x11currentTickOfNode\x12\x19\n" +
	"\btx_count\x18\x03 \x01(\rR\atxCount\x12U\n" +
	"\rstatus_per_tx\x18\x04 \x03(\v21.qubic.v1.TickTransactionsStatus.StatusPerTxEntryR\vstatusPerTx\x1a>\n" +
	"\x10StatusPerTxEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B/Z-github.com/qubic/go-qubic/v2/proto/v1;qubicpbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_core_proto_goTypes = []any{
	(*EntityInfo)(nil),                    // 0: qubic.v1.EntityInfo
	(*Computors)(nil),                     // 1: qubic.v1.Computors
	(*QuorumVote)(nil),                    // 2: qubic.v1.QuorumVote
	(*TickData)(nil),                      // 3: qubic.v1.TickData
	(*TickInfo)(nil),                      // 4: qubic.v1.TickInfo
	(*Transaction)(nil),                   // 5: qubic.v1.Transaction
	(*TickTransactions)(nil),              // 6: qubic.v1.TickTransactions
	(*TickTransactionsStatus)(nil),        // 7: qubic.v1.TickTransactionsStatus
	(*EntityInfo_Entity)(nil),             // 8: qubic.v1.EntityInfo.Entity
	(*QuorumVote_SharedVote)(nil),         // 9: qubic.v1.QuorumVote.SharedVote
	(*QuorumVote_GroupedSharedVotes)(nil), // 10: qubic.v1.QuorumVote.GroupedSharedVotes
	(*QuorumVote_SaltedVote)(nil),         // 11: qubic.v1.QuorumVote.SaltedVote
	nil,                                   // 12: qubic.v1.QuorumVote.SaltedVotesPerComputorIndexEntry
	nil,                                   // 13: qubic.v1.TickTransactionsStatus.StatusPerTxEntry
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_core_proto_depIdxs = []int32{
	8,  // 0: qubic.v1.EntityInfo.entity:type_name -> qubic.v1.EntityInfo.Entity
	10, // 1: qubic.v1.QuorumVote.shared_votes:type_name -> qubic.v1.QuorumVote.GroupedSharedVotes
	12, // 2: qubic.v1.QuorumVote.salted_votes_per_computor_index:type_name -> qubic.v1.QuorumVote.SaltedVotesPerComputorIndexEntry
	14, // 3: qubic.v1.TickData.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 4: qubic.v1.TickTransactions.transactions:type_name -> qubic.v1.Transaction
	13, // 5: qubic.v1.TickTransactionsStatus.status_per_tx:type_name -> qubic.v1.TickTransactionsStatus.StatusPerTxEntry
	14, // 6: qubic.v1.QuorumVote.SharedVote.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 7: qubic.v1.QuorumVote.GroupedSharedVotes.vote:type_name -> qubic.v1.QuorumVote.SharedVote
	11, // 8: qubic.v1.QuorumVote.SaltedVotesPerComputorIndexEntry.value:type_name -> qubic.v1.QuorumVote.SaltedVote
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
