// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: core_service.proto

package qubicpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEntityInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityInfoRequest) Reset() {
	*x = GetEntityInfoRequest{}
	mi := &file_core_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityInfoRequest) ProtoMessage() {}

func (x *GetEntityInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityInfoRequest.ProtoReflect.Descriptor instead.
func (*GetEntityInfoRequest) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetEntityInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTickQuorumVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickQuorumVoteRequest) Reset() {
	*x = GetTickQuorumVoteRequest{}
	mi := &file_core_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickQuorumVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickQuorumVoteRequest) ProtoMessage() {}

func (x *GetTickQuorumVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickQuorumVoteRequest.ProtoReflect.Descriptor instead.
func (*GetTickQuorumVoteRequest) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTickQuorumVoteRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type GetTickDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickDataRequest) Reset() {
	*x = GetTickDataRequest{}
	mi := &file_core_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickDataRequest) ProtoMessage() {}

func (x *GetTickDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickDataRequest.ProtoReflect.Descriptor instead.
func (*GetTickDataRequest) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTickDataRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type GetTickTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickTransactionsRequest) Reset() {
	*x = GetTickTransactionsRequest{}
	mi := &file_core_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickTransactionsRequest) ProtoMessage() {}

func (x *GetTickTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTickTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTickTransactionsRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type GetTickTransactionsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickTransactionsStatusRequest) Reset() {
	*x = GetTickTransactionsStatusRequest{}
	mi := &file_core_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickTransactionsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickTransactionsStatusRequest) ProtoMessage() {}

func (x *GetTickTransactionsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickTransactionsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTickTransactionsStatusRequest) Descriptor() ([]byte, []int) {
	return file_core_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTickTransactionsStatusRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

var File_core_service_proto protoreflect.FileDescriptor

const file_core_service_proto_rawDesc = "" +
	"\n" +
	"\x12core_service.proto\x12\bqubic.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"core.proto\"&\n" +
	"\x14GetEntityInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x18GetTickQuorumVoteRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"(\n" +
	"\x12GetTickDataRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"0\n" +
	"\x1aGetTickTransactionsRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"6\n" +
	" GetTickTransactionsStatusRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick2\xa2\x06\n" +
	"\vCoreService\x12W\n" +
	"\vGetTickInfo\x12\x16.google.protobuf.Empty\x1a\x12.qubic.v1.TickInfo\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/core/getTickInfo\x12h\n" +
	"\rGetEntityInfo\x12\x1e.qubic.v1.GetEntityInfoRequest\x1a\x14.qubic.v1.EntityInfo\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/core/getEntityInfo\x12Z\n" +
	"\fGetComputors\x12\x16.google.protobuf.Empty\x1a\x13.qubic.v1.Computors\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/core/getComputors\x12t\n" +
	"\x11GetTickQuorumVote\x12\".qubic.v1.GetTickQuorumVoteRequest\x1a\x14.qubic.v1.QuorumVote\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/core/getTickQuorumVote\x12`\n" +
	"\vGetTickData\x12\x1c.qubic.v1.GetTickDataRequest\x1a\x12.qubic.v1.TickData\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/core/getTickData\x12\x80\x01\n" +
	"\x13GetTickTransactions\x12$.qubic.v1.GetTickTransactionsRequest\x1a\x1a.qubic.v1.TickTransactions\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/core/getTickTransactions\x12\x98\x01\n" +
	"\x19GetTickTransactionsStatus\x12*.qubic.v1.GetTickTransactionsStatusRequest\x1a .qubic.v1.TickTransactionsStatus\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/core/getTickTransactionsStatusB/Z-github.com/qubic/go-qubic/v2/proto/v1;qubicpbb\x06proto3"

var (
	file_core_service_proto_rawDescOnce sync.Once
	file_core_service_proto_rawDescData []byte
)

func file_core_service_proto_rawDescGZIP() []byte {
	file_core_service_proto_rawDescOnce.Do(func() {
		file_core_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_service_proto_rawDesc), len(file_core_service_proto_rawDesc)))
	})
	return file_core_service_proto_rawDescData
}

var file_core_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_service_proto_goTypes = []any{
	(*GetEntityInfoRequest)(nil),             // 0: qubic.v1.GetEntityInfoRequest
	(*GetTickQuorumVoteRequest)(nil),         // 1: qubic.v1.GetTickQuorumVoteRequest
	(*GetTickDataRequest)(nil),               // 2: qubic.v1.GetTickDataRequest
	(*GetTickTransactionsRequest)(nil),       // 3: qubic.v1.GetTickTransactionsRequest
	(*GetTickTransactionsStatusRequest)(nil), // 4: qubic.v1.GetTickTransactionsStatusRequest
	(*emptypb.Empty)(nil),                    // 5: google.protobuf.Empty
	(*TickInfo)(nil),                         // 6: qubic.v1.TickInfo
	(*EntityInfo)(nil),                       // 7: qubic.v1.EntityInfo
	(*Computors)(nil),                        // 8: qubic.v1.Computors
	(*QuorumVote)(nil),                       // 9: qubic.v1.QuorumVote
	(*TickData)(nil),                         // 10: qubic.v1.TickData
	(*TickTransactions)(nil),                 // 11: qubic.v1.TickTransactions
	(*TickTransactionsStatus)(nil),           // 12: qubic.v1.TickTransactionsStatus
}
var file_core_service_proto_depIdxs = []int32{
	5,  // 0: qubic.v1.CoreService.GetTickInfo:input_type -> google.protobuf.Empty
	0,  // 1: qubic.v1.CoreService.GetEntityInfo:input_type -> qubic.v1.GetEntityInfoRequest
	5,  // 2: qubic.v1.CoreService.GetComputors:input_type -> google.protobuf.Empty
	1,  // 3: qubic.v1.CoreService.GetTickQuorumVote:input_type -> qubic.v1.GetTickQuorumVoteRequest
	2,  // 4: qubic.v1.CoreService.GetTickData:input_type -> qubic.v1.GetTickDataRequest
	3,  // 5: qubic.v1.CoreService.GetTickTransactions:input_type -> qubic.v1.GetTickTransactionsRequest
	4,  // 6: qubic.v1.CoreService.GetTickTransactionsStatus:input_type -> qubic.v1.GetTickTransactionsStatusRequest
	6,  // 7: qubic.v1.CoreService.GetTickInfo:output_type -> qubic.v1.TickInfo
	7,  // 8: qubic.v1.CoreService.GetEntityInfo:output_type -> qubic.v1.EntityInfo
	8,  // 9: qubic.v1.CoreService.GetComputors:output_type -> qubic.v1.Computors
	9,  // 10: qubic.v1.CoreService.GetTickQuorumVote:output_type -> qubic.v1.QuorumVote
	10, // 11: qubic.v1.CoreService.GetTickData:output_type -> qubic.v1.TickData
	11, // 12: qubic.v1.CoreService.GetTickTransactions:output_type -> qubic.v1.TickTransactions
	12, // 13: qubic.v1.CoreService.GetTickTransactionsStatus:output_type -> qubic.v1.TickTransactionsStatus
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_core_service_proto_init() }
func file_core_service_proto_init() {
	if File_core_service_proto != nil {
		return
	}
	file_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_service_proto_rawDesc), len(file_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_service_proto_goTypes,
		DependencyIndexes: file_core_service_proto_depIdxs,
		MessageInfos:      file_core_service_proto_msgTypes,
	}.Build()
	File_core_service_proto = out.File
	file_core_service_proto_goTypes = nil
	file_core_service_proto_depIdxs = nil
}
