// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: events.proto

package qubicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Event_Header          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EventType     uint32                 `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventSize     uint32                 `protobuf:"varint,3,opt,name=event_size,json=eventSize,proto3" json:"event_size,omitempty"`
	EventData     string                 `protobuf:"bytes,4,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetHeader() *Event_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Event) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Event) GetEventSize() uint32 {
	if x != nil {
		return x.EventSize
	}
	return 0
}

func (x *Event) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

type TransactionEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvents) Reset() {
	*x = TransactionEvents{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvents) ProtoMessage() {}

func (x *TransactionEvents) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvents.ProtoReflect.Descriptor instead.
func (*TransactionEvents) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionEvents) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionEvents) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type TickEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	TxEvents      []*TransactionEvents   `protobuf:"bytes,2,rep,name=tx_events,json=txEvents,proto3" json:"tx_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickEvents) Reset() {
	*x = TickEvents{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickEvents) ProtoMessage() {}

func (x *TickEvents) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickEvents.ProtoReflect.Descriptor instead.
func (*TickEvents) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *TickEvents) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickEvents) GetTxEvents() []*TransactionEvents {
	if x != nil {
		return x.TxEvents
	}
	return nil
}

type Event_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Tmp           uint32                 `protobuf:"varint,3,opt,name=tmp,proto3" json:"tmp,omitempty"`
	EventId       uint64                 `protobuf:"varint,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventDigest   uint64                 `protobuf:"varint,5,opt,name=event_digest,json=eventDigest,proto3" json:"event_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Header) Reset() {
	*x = Event_Header{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Header) ProtoMessage() {}

func (x *Event_Header) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Header.ProtoReflect.Descriptor instead.
func (*Event_Header) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_Header) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Event_Header) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Event_Header) GetTmp() uint32 {
	if x != nil {
		return x.Tmp
	}
	return 0
}

func (x *Event_Header) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event_Header) GetEventDigest() uint64 {
	if x != nil {
		return x.EventDigest
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\bqubic.v1\"\x99\x02\n" +
	"\x05Event\x12.\n" +
	"\x06header\x18\x01 \x01(\v2\x16.qubic.v1.Event.HeaderR\x06header\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\rR\teventType\x12\x1d\n" +
	"\n" +
	"event_size\x18\x03 \x01(\rR\teventSize\x12\x1d\n" +
	"\n" +
	"event_data\x18\x04 \x01(\tR\teventData\x1a\x82\x01\n" +
	"\x06Header\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12\x10\n" +
	"\x03tmp\x18\x03 \x01(\rR\x03tmp\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\x04R\aeventId\x12!\n" +
	"\fevent_digest\x18\x05 \x01(\x04R\veventDigest\"Q\n" +
	"\x11TransactionEvents\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12'\n" +
	"\x06events\x18\x02 \x03(\v2\x0f.qubic.v1.EventR\x06events\"Z\n" +
	"\n" +
	"TickEvents\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x128\n" +
	"\ttx_events\x18\x02 \x03(\v2\x1b.qubic.v1.TransactionEventsR\btxEventsB/Z-github.com/qubic/go-qubic/v2/proto/v1;qubicpbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_events_proto_goTypes = []any{
	(*Event)(nil),             // 0: qubic.v1.Event
	(*TransactionEvents)(nil), // 1: qubic.v1.TransactionEvents
	(*TickEvents)(nil),        // 2: qubic.v1.TickEvents
	(*Event_Header)(nil),      // 3: qubic.v1.Event.Header
}
var file_events_proto_depIdxs = []int32{
	3, // 0: qubic.v1.Event.header:type_name -> qubic.v1.Event.Header
	0, // 1: qubic.v1.TransactionEvents.events:type_name -> qubic.v1.Event
	1, // 2: qubic.v1.TickEvents.tx_events:type_name -> qubic.v1.TransactionEvents
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
