// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: quottery_service.proto

package qubicpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetId         uint32                 `protobuf:"varint,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetInfoRequest) Reset() {
	*x = GetBetInfoRequest{}
	mi := &file_quottery_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetInfoRequest) ProtoMessage() {}

func (x *GetBetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quottery_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBetInfoRequest) Descriptor() ([]byte, []int) {
	return file_quottery_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetBetInfoRequest) GetBetId() uint32 {
	if x != nil {
		return x.BetId
	}
	return 0
}

type GetActiveBetsByCreatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveBetsByCreatorRequest) Reset() {
	*x = GetActiveBetsByCreatorRequest{}
	mi := &file_quottery_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveBetsByCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveBetsByCreatorRequest) ProtoMessage() {}

func (x *GetActiveBetsByCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quottery_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveBetsByCreatorRequest.ProtoReflect.Descriptor instead.
func (*GetActiveBetsByCreatorRequest) Descriptor() ([]byte, []int) {
	return file_quottery_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetActiveBetsByCreatorRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type GetBettorsByBetOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetId         uint32                 `protobuf:"varint,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	BetOption     uint32                 `protobuf:"varint,2,opt,name=bet_option,json=betOption,proto3" json:"bet_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBettorsByBetOptionRequest) Reset() {
	*x = GetBettorsByBetOptionRequest{}
	mi := &file_quottery_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBettorsByBetOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBettorsByBetOptionRequest) ProtoMessage() {}

func (x *GetBettorsByBetOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quottery_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBettorsByBetOptionRequest.ProtoReflect.Descriptor instead.
func (*GetBettorsByBetOptionRequest) Descriptor() ([]byte, []int) {
	return file_quottery_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBettorsByBetOptionRequest) GetBetId() uint32 {
	if x != nil {
		return x.BetId
	}
	return 0
}

func (x *GetBettorsByBetOptionRequest) GetBetOption() uint32 {
	if x != nil {
		return x.BetOption
	}
	return 0
}

var File_quottery_service_proto protoreflect.FileDescriptor

const file_quottery_service_proto_rawDesc = "" +
	"\n" +
	"\x16quottery_service.proto\x12\bqubic.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0equottery.proto\"*\n" +
	"\x11GetBetInfoRequest\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\rR\x05betId\">\n" +
	"\x1dGetActiveBetsByCreatorRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\"T\n" +
	"\x1cGetBettorsByBetOptionRequest\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\rR\x05betId\x12\x1d\n" +
	"\n" +
	"bet_option\x18\x02 \x01(\rR\tbetOption2\xc4\x04\n" +
	"\x0fQuotteryService\x12^\n" +
	"\fGetBasicInfo\x12\x16.google.protobuf.Empty\x1a\x13.qubic.v1.BasicInfo\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/quottery/getBasicInfo\x12]\n" +
	"\n" +
	"GetBetInfo\x12\x1b.qubic.v1.GetBetInfoRequest\x1a\x11.qubic.v1.BetInfo\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/quottery/getBetInfo\x12a\n" +
	"\rGetActiveBets\x12\x16.google.protobuf.Empty\x1a\x14.qubic.v1.ActiveBets\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/quottery/getActiveBets\x12\x84\x01\n" +
	"\x16GetActiveBetsByCreator\x12'.qubic.v1.GetActiveBetsByCreatorRequest\x1a\x14.qubic.v1.ActiveBets\"+\x82\xd3\xe4\x93\x02%\x12#/v1/quottery/getActiveBetsByCreator\x12\x87\x01\n" +
	"\x15GetBettorsByBetOption\x12&.qubic.v1.GetBettorsByBetOptionRequest\x1a\x1a.qubic.v1.BetOptionBettors\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/quottery/getBettorsByBetOptionB/Z-github.com/qubic/go-qubic/v2/proto/v1;qubicpbb\x06proto3"

var (
	file_quottery_service_proto_rawDescOnce sync.Once
	file_quottery_service_proto_rawDescData []byte
)

func file_quottery_service_proto_rawDescGZIP() []byte {
	file_quottery_service_proto_rawDescOnce.Do(func() {
		file_quottery_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quottery_service_proto_rawDesc), len(file_quottery_service_proto_rawDesc)))
	})
	return file_quottery_service_proto_rawDescData
}

var file_quottery_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_quottery_service_proto_goTypes = []any{
	(*GetBetInfoRequest)(nil),             // 0: qubic.v1.GetBetInfoRequest
	(*GetActiveBetsByCreatorRequest)(nil), // 1: qubic.v1.GetActiveBetsByCreatorRequest
	(*GetBettorsByBetOptionRequest)(nil),  // 2: qubic.v1.GetBettorsByBetOptionRequest
	(*emptypb.Empty)(nil),                 // 3: google.protobuf.Empty
	(*BasicInfo)(nil),                     // 4: qubic.v1.BasicInfo
	(*BetInfo)(nil),                       // 5: qubic.v1.BetInfo
	(*ActiveBets)(nil),                    // 6: qubic.v1.ActiveBets
	(*BetOptionBettors)(nil),              // 7: qubic.v1.BetOptionBettors
}
var file_quottery_service_proto_depIdxs = []int32{
	3, // 0: qubic.v1.QuotteryService.GetBasicInfo:input_type -> google.protobuf.Empty
	0, // 1: qubic.v1.QuotteryService.GetBetInfo:input_type -> qubic.v1.GetBetInfoRequest
	3, // 2: qubic.v1.QuotteryService.GetActiveBets:input_type -> google.protobuf.Empty
	1, // 3: qubic.v1.QuotteryService.GetActiveBetsByCreator:input_type -> qubic.v1.GetActiveBetsByCreatorRequest
	2, // 4: qubic.v1.QuotteryService.GetBettorsByBetOption:input_type -> qubic.v1.GetBettorsByBetOptionRequest
	4, // 5: qubic.v1.QuotteryService.GetBasicInfo:output_type -> qubic.v1.BasicInfo
	5, // 6: qubic.v1.QuotteryService.GetBetInfo:output_type -> qubic.v1.BetInfo
	6, // 7: qubic.v1.QuotteryService.GetActiveBets:output_type -> qubic.v1.ActiveBets
	6, // 8: qubic.v1.QuotteryService.GetActiveBetsByCreator:output_type -> qubic.v1.ActiveBets
	7, // 9: qubic.v1.QuotteryService.GetBettorsByBetOption:output_type -> qubic.v1.BetOptionBettors
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quottery_service_proto_init() }
func file_quottery_service_proto_init() {
	if File_quottery_service_proto != nil {
		return
	}
	file_quottery_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quottery_service_proto_rawDesc), len(file_quottery_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quottery_service_proto_goTypes,
		DependencyIndexes: file_quottery_service_proto_depIdxs,
		MessageInfos:      file_quottery_service_proto_msgTypes,
	}.Build()
	File_quottery_service_proto = out.File
	file_quottery_service_proto_goTypes = nil
	file_quottery_service_proto_depIdxs = nil
}
