// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: qx.proto

package qubicpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fees struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssetIssuanceFee uint32                 `protobuf:"varint,1,opt,name=asset_issuance_fee,json=assetIssuanceFee,proto3" json:"asset_issuance_fee,omitempty"`
	TransferFee      uint32                 `protobuf:"varint,2,opt,name=transfer_fee,json=transferFee,proto3" json:"transfer_fee,omitempty"`
	TradeFee         uint32                 `protobuf:"varint,3,opt,name=trade_fee,json=tradeFee,proto3" json:"trade_fee,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Fees) Reset() {
	*x = Fees{}
	mi := &file_qx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fees) ProtoMessage() {}

func (x *Fees) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fees.ProtoReflect.Descriptor instead.
func (*Fees) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{0}
}

func (x *Fees) GetAssetIssuanceFee() uint32 {
	if x != nil {
		return x.AssetIssuanceFee
	}
	return 0
}

func (x *Fees) GetTransferFee() uint32 {
	if x != nil {
		return x.TransferFee
	}
	return 0
}

func (x *Fees) GetTradeFee() uint32 {
	if x != nil {
		return x.TradeFee
	}
	return 0
}

type AssetOrders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*AssetOrders_Order   `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetOrders) Reset() {
	*x = AssetOrders{}
	mi := &file_qx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOrders) ProtoMessage() {}

func (x *AssetOrders) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOrders.ProtoReflect.Descriptor instead.
func (*AssetOrders) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{1}
}

func (x *AssetOrders) GetOrders() []*AssetOrders_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type EntityOrders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*EntityOrders_Order  `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityOrders) Reset() {
	*x = EntityOrders{}
	mi := &file_qx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityOrders) ProtoMessage() {}

func (x *EntityOrders) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityOrders.ProtoReflect.Descriptor instead.
func (*EntityOrders) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{2}
}

func (x *EntityOrders) GetOrders() []*EntityOrders_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetAssetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetName     string                 `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	IssuerId      string                 `protobuf:"bytes,2,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetOrdersRequest) Reset() {
	*x = GetAssetOrdersRequest{}
	mi := &file_qx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetOrdersRequest) ProtoMessage() {}

func (x *GetAssetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAssetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetOrdersRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *GetAssetOrdersRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *GetAssetOrdersRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetEntityOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityOrdersRequest) Reset() {
	*x = GetEntityOrdersRequest{}
	mi := &file_qx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityOrdersRequest) ProtoMessage() {}

func (x *GetEntityOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetEntityOrdersRequest) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntityOrdersRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetEntityOrdersRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AssetOrders_Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntityId       string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Price          int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	NumberOfShares int64                  `protobuf:"varint,3,opt,name=number_of_shares,json=numberOfShares,proto3" json:"number_of_shares,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetOrders_Order) Reset() {
	*x = AssetOrders_Order{}
	mi := &file_qx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOrders_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOrders_Order) ProtoMessage() {}

func (x *AssetOrders_Order) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOrders_Order.ProtoReflect.Descriptor instead.
func (*AssetOrders_Order) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AssetOrders_Order) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AssetOrders_Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AssetOrders_Order) GetNumberOfShares() int64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

type EntityOrders_Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IssuerId       string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	AssetName      string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Price          int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	NumberOfShares int64                  `protobuf:"varint,4,opt,name=number_of_shares,json=numberOfShares,proto3" json:"number_of_shares,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityOrders_Order) Reset() {
	*x = EntityOrders_Order{}
	mi := &file_qx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityOrders_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityOrders_Order) ProtoMessage() {}

func (x *EntityOrders_Order) ProtoReflect() protoreflect.Message {
	mi := &file_qx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityOrders_Order.ProtoReflect.Descriptor instead.
func (*EntityOrders_Order) Descriptor() ([]byte, []int) {
	return file_qx_proto_rawDescGZIP(), []int{2, 0}
}

func (x *EntityOrders_Order) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *EntityOrders_Order) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *EntityOrders_Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EntityOrders_Order) GetNumberOfShares() int64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

var File_qx_proto protoreflect.FileDescriptor

const file_qx_proto_rawDesc = "" +
	"\n" +
	"\bqx.proto\x12\bqubic.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"t\n" +
	"\x04Fees\x12,\n" +
	"\x12asset_issuance_fee\x18\x01 \x01(\rR\x10assetIssuanceFee\x12!\n" +
	"\ftransfer_fee\x18\x02 \x01(\rR\vtransferFee\x12\x1b\n" +
	"\ttrade_fee\x18\x03 \x01(\rR\btradeFee\"\xa8\x01\n" +
	"\vAssetOrders\x123\n" +
	"\x06orders\x18\x01 \x03(\v2\x1b.qubic.v1.AssetOrders.OrderR\x06orders\x1ad\n" +
	"\x05Order\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12(\n" +
	"\x10number_of_shares\x18\x03 \x01(\x03R\x0enumberOfShares\"\xca\x01\n" +
	"\fEntityOrders\x124\n" +
	"\x06orders\x18\x01 \x03(\v2\x1c.qubic.v1.EntityOrders.OrderR\x06orders\x1a\x83\x01\n" +
	"\x05Order\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12(\n" +
	"\x10number_of_shares\x18\x04 \x01(\x03R\x0enumberOfShares\"k\n" +
	"\x15GetAssetOrdersRequest\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\tR\tassetName\x12\x1b\n" +
	"\tissuer_id\x18\x02 \x01(\tR\bissuerId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"M\n" +
	"\x16GetEntityOrdersRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset2\x9a\x04\n" +
	"\tQxService\x12I\n" +
	"\aGetFees\x12\x16.google.protobuf.Empty\x1a\x0e.qubic.v1.Fees\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/qx/getFees\x12m\n" +
	"\x11GetAssetAskOrders\x12\x1f.qubic.v1.GetAssetOrdersRequest\x1a\x15.qubic.v1.AssetOrders\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/qx/getAssetAskOrders\x12m\n" +
	"\x11GetAssetBidOrders\x12\x1f.qubic.v1.GetAssetOrdersRequest\x1a\x15.qubic.v1.AssetOrders\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/qx/getAssetBidOrders\x12q\n" +
	"\x12GetEntityAskOrders\x12 .qubic.v1.GetEntityOrdersRequest\x1a\x16.qubic.v1.EntityOrders\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/qx/getEntityAskOrders\x12q\n" +
	"\x12GetEntityBidOrders\x12 .qubic.v1.GetEntityOrdersRequest\x1a\x16.qubic.v1.EntityOrders\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/qx/getEntityBidOrdersB/Z-github.com/qubic/go-qubic/v2/proto/v1;qubicpbb\x06proto3"

var (
	file_qx_proto_rawDescOnce sync.Once
	file_qx_proto_rawDescData []byte
)

func file_qx_proto_rawDescGZIP() []byte {
	file_qx_proto_rawDescOnce.Do(func() {
		file_qx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qx_proto_rawDesc), len(file_qx_proto_rawDesc)))
	})
	return file_qx_proto_rawDescData
}

var file_qx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_qx_proto_goTypes = []any{
	(*Fees)(nil),                   // 0: qubic.v1.Fees
	(*AssetOrders)(nil),            // 1: qubic.v1.AssetOrders
	(*EntityOrders)(nil),           // 2: qubic.v1.EntityOrders
	(*GetAssetOrdersRequest)(nil),  // 3: qubic.v1.GetAssetOrdersRequest
	(*GetEntityOrdersRequest)(nil), // 4: qubic.v1.GetEntityOrdersRequest
	(*AssetOrders_Order)(nil),      // 5: qubic.v1.AssetOrders.Order
	(*EntityOrders_Order)(nil),     // 6: qubic.v1.EntityOrders.Order
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_qx_proto_depIdxs = []int32{
	5, // 0: qubic.v1.AssetOrders.orders:type_name -> qubic.v1.AssetOrders.Order
	6, // 1: qubic.v1.EntityOrders.orders:type_name -> qubic.v1.EntityOrders.Order
	7, // 2: qubic.v1.QxService.GetFees:input_type -> google.protobuf.Empty
	3, // 3: qubic.v1.QxService.GetAssetAskOrders:input_type -> qubic.v1.GetAssetOrdersRequest
	3, // 4: qubic.v1.QxService.GetAssetBidOrders:input_type -> qubic.v1.GetAssetOrdersRequest
	4, // 5: qubic.v1.QxService.GetEntityAskOrders:input_type -> qubic.v1.GetEntityOrdersRequest
	4, // 6: qubic.v1.QxService.GetEntityBidOrders:input_type -> qubic.v1.GetEntityOrdersRequest
	0, // 7: qubic.v1.QxService.GetFees:output_type -> qubic.v1.Fees
	1, // 8: qubic.v1.QxService.GetAssetAskOrders:output_type -> qubic.v1.AssetOrders
	1, // 9: qubic.v1.QxService.GetAssetBidOrders:output_type -> qubic.v1.AssetOrders
	2, // 10: qubic.v1.QxService.GetEntityAskOrders:output_type -> qubic.v1.EntityOrders
	2, // 11: qubic.v1.QxService.GetEntityBidOrders:output_type -> qubic.v1.EntityOrders
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_qx_proto_init() }
func file_qx_proto_init() {
	if File_qx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qx_proto_rawDesc), len(file_qx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qx_proto_goTypes,
		DependencyIndexes: file_qx_proto_depIdxs,
		MessageInfos:      file_qx_proto_msgTypes,
	}.Build()
	File_qx_proto = out.File
	file_qx_proto_goTypes = nil
	file_qx_proto_depIdxs = nil
}
